// Datenschutzerklärung content, injected into the #datenschutz section.
// Base text generated with the eRecht24 DSGVO generator; the Proton, KI
// (Anthropic Claude) and ProvenExpert blocks plus the Netlify DPF sentence
// and the 12-month retention rule are project-specific additions.
// German is the authoritative version.
window.TT_LEGAL = {
  datenschutz: `
<h2>Datenschutzerkl&auml;rung</h2>
<h3>1. Datenschutz auf einen Blick</h3>
<h4>Allgemeine Hinweise</h4>
<p>Die folgenden Hinweise geben einen einfachen &Uuml;berblick dar&uuml;ber, was mit Ihren personenbezogenen Daten passiert, wenn Sie diese Website besuchen. Personenbezogene Daten sind alle Daten, mit denen Sie pers&ouml;nlich identifiziert werden k&ouml;nnen. Ausf&uuml;hrliche Informationen zum Thema Datenschutz entnehmen Sie unserer unter diesem Text aufgef&uuml;hrten Datenschutzerkl&auml;rung.</p>
<h4>Datenerfassung auf dieser Website</h4>
<p><strong>Wer ist verantwortlich f&uuml;r die Datenerfassung auf dieser Website?</strong></p>
<p>Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber. Dessen Kontaktdaten k&ouml;nnen Sie dem Abschnitt &bdquo;Hinweis zur verantwortlichen Stelle&ldquo; in dieser Datenschutzerkl&auml;rung entnehmen.</p>
<p><strong>Wie erfassen wir Ihre Daten?</strong></p>
<p>Ihre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen. Hierbei kann es sich z.&nbsp;B. um Daten handeln, die Sie uns per E-Mail oder WhatsApp &uuml;bermitteln.</p>
<p>Andere Daten werden automatisch oder nach Ihrer Einwilligung beim Besuch der Website durch unsere IT-Systeme erfasst. Das sind vor allem technische Daten (z.&nbsp;B. Internetbrowser, Betriebssystem oder Uhrzeit des Seitenaufrufs). Die Erfassung dieser Daten erfolgt automatisch, sobald Sie diese Website betreten.</p>
<p><strong>Wof&uuml;r nutzen wir Ihre Daten?</strong></p>
<p>Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gew&auml;hrleisten. Sofern &uuml;ber die Website oder die genannten Kontaktkan&auml;le Vertr&auml;ge geschlossen oder angebahnt werden, werden die &uuml;bermittelten Daten auch f&uuml;r Vertragsangebote, Anfragen oder die Erbringung der Traumdeutung verarbeitet.</p>
<p><strong>Welche Rechte haben Sie bez&uuml;glich Ihrer Daten?</strong></p>
<p>Sie haben jederzeit das Recht, unentgeltlich Auskunft &uuml;ber Herkunft, Empf&auml;nger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Sie haben au&szlig;erdem ein Recht, die Berichtigung oder L&ouml;schung dieser Daten zu verlangen. Wenn Sie eine Einwilligung zur Datenverarbeitung erteilt haben, k&ouml;nnen Sie diese Einwilligung jederzeit f&uuml;r die Zukunft widerrufen. Au&szlig;erdem haben Sie das Recht, unter bestimmten Umst&auml;nden die Einschr&auml;nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Des Weiteren steht Ihnen ein Beschwerderecht bei der zust&auml;ndigen Aufsichtsbeh&ouml;rde zu.</p>
<p>Hierzu sowie zu weiteren Fragen zum Thema Datenschutz k&ouml;nnen Sie sich jederzeit an uns wenden.</p>

<h3>2. Hosting</h3>
<p>Wir hosten die Inhalte unserer Website bei folgendem Anbieter:</p>
<h4>Externes Hosting</h4>
<p>Diese Website wird extern gehostet. Die personenbezogenen Daten, die auf dieser Website erfasst werden, werden auf den Servern des Hosters gespeichert. Hierbei kann es sich v.&nbsp;a. um IP-Adressen, Kontaktanfragen, Meta- und Kommunikationsdaten, Vertragsdaten, Kontaktdaten, Namen, Websitezugriffe und sonstige Daten, die &uuml;ber eine Website generiert werden, handeln.</p>
<p>Das externe Hosting erfolgt zum Zwecke der Vertragserf&uuml;llung gegen&uuml;ber unseren potenziellen und bestehenden Kunden (Art. 6 Abs. 1 lit. b DSGVO) und im Interesse einer sicheren, schnellen und effizienten Bereitstellung unseres Online-Angebots durch einen professionellen Anbieter (Art. 6 Abs. 1 lit. f DSGVO).</p>
<p>Unser Hoster wird Ihre Daten nur insoweit verarbeiten, wie dies zur Erf&uuml;llung seiner Leistungspflichten erforderlich ist und unsere Weisungen in Bezug auf diese Daten befolgen.</p>
<p>Wir setzen folgenden Hoster ein:</p>
<p>Netlify, Inc.<br />44 Montgomery Street, Suite 300<br />San Francisco, CA 94104<br />USA</p>
<p>Die Übermittlung personenbezogener Daten in die USA wird auf den EU-US Data Privacy Framework gestützt, unter dem Netlify, Inc. zertifiziert ist (Angemessenheitsbeschluss der EU-Kommission, Art. 45 DSGVO); ergänzend sind die EU-Standardvertragsklauseln vereinbart.</p>
<h4>Auftragsverarbeitung</h4>
<p>Wir haben einen Vertrag &uuml;ber Auftragsverarbeitung (AVV) zur Nutzung des oben genannten Dienstes geschlossen. Hierbei handelt es sich um einen datenschutzrechtlich vorgeschriebenen Vertrag, der gew&auml;hrleistet, dass dieser die personenbezogenen Daten unserer Websitebesucher nur nach unseren Weisungen und unter Einhaltung der DSGVO verarbeitet.</p>

<h3>3. Allgemeine Hinweise und Pflichtinformationen</h3>
<h4>Datenschutz</h4>
<p>Die Betreiber dieser Seiten nehmen den Schutz Ihrer pers&ouml;nlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend den gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerkl&auml;rung.</p>
<p>Wenn Sie diese Website benutzen, werden verschiedene personenbezogene Daten erhoben. Personenbezogene Daten sind Daten, mit denen Sie pers&ouml;nlich identifiziert werden k&ouml;nnen. Die vorliegende Datenschutzerkl&auml;rung erl&auml;utert, welche Daten wir erheben und wof&uuml;r wir sie nutzen. Sie erl&auml;utert auch, wie und zu welchem Zweck das geschieht.</p>
<p>Wir weisen darauf hin, dass die Daten&uuml;bertragung im Internet (z.&nbsp;B. bei der Kommunikation per E-Mail) Sicherheitsl&uuml;cken aufweisen kann. Ein l&uuml;ckenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht m&ouml;glich.</p>
<h4>Hinweis zur verantwortlichen Stelle</h4>
<p>Die verantwortliche Stelle f&uuml;r die Datenverarbeitung auf dieser Website ist:</p>
<p>Mark Anthony Irwin<br />Parkstra&szlig;e 15<br />47906 Kempen</p>
<p>Telefon: +49 151 50317725<br />E-Mail: kontakt@traum-theater.de</p>
<p>Verantwortliche Stelle ist die nat&uuml;rliche oder juristische Person, die allein oder gemeinsam mit anderen &uuml;ber die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten (z.&nbsp;B. Namen, E-Mail-Adressen o. &Auml;.) entscheidet.</p>
<h4>Speicherdauer</h4>
<p>Soweit innerhalb dieser Datenschutzerkl&auml;rung keine speziellere Speicherdauer genannt wurde, verbleiben Ihre personenbezogenen Daten bei uns, bis der Zweck f&uuml;r die Datenverarbeitung entf&auml;llt. Wenn Sie ein berechtigtes L&ouml;schersuchen geltend machen oder eine Einwilligung zur Datenverarbeitung widerrufen, werden Ihre Daten gel&ouml;scht, sofern wir keine anderen rechtlich zul&auml;ssigen Gr&uuml;nde f&uuml;r die Speicherung Ihrer personenbezogenen Daten haben (z.&nbsp;B. steuer- oder handelsrechtliche Aufbewahrungsfristen); im letztgenannten Fall erfolgt die L&ouml;schung nach Fortfall dieser Gr&uuml;nde.</p>
<h4>Allgemeine Hinweise zu den Rechtsgrundlagen der Datenverarbeitung auf dieser Website</h4>
<p>Sofern Sie in die Datenverarbeitung eingewilligt haben, verarbeiten wir Ihre personenbezogenen Daten auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO bzw. Art. 9 Abs. 2 lit. a DSGVO, sofern besondere Datenkategorien nach Art. 9 Abs. 1 DSGVO verarbeitet werden. Im Falle einer ausdr&uuml;cklichen Einwilligung in die &Uuml;bertragung personenbezogener Daten in Drittstaaten erfolgt die Datenverarbeitung au&szlig;erdem auf Grundlage von Art. 49 Abs. 1 lit. a DSGVO. Sind Ihre Daten zur Vertragserf&uuml;llung oder zur Durchf&uuml;hrung vorvertraglicher Ma&szlig;nahmen erforderlich, verarbeiten wir Ihre Daten auf Grundlage des Art. 6 Abs. 1 lit. b DSGVO. Des Weiteren verarbeiten wir Ihre Daten, sofern diese zur Erf&uuml;llung einer rechtlichen Verpflichtung erforderlich sind, auf Grundlage von Art. 6 Abs. 1 lit. c DSGVO. Die Datenverarbeitung kann ferner auf Grundlage unseres berechtigten Interesses nach Art. 6 Abs. 1 lit. f DSGVO erfolgen.</p>
<h4>Empf&auml;nger von personenbezogenen Daten</h4>
<p>Im Rahmen unserer Gesch&auml;ftst&auml;tigkeit arbeiten wir mit verschiedenen externen Stellen zusammen. Dabei ist teilweise auch eine &Uuml;bermittlung von personenbezogenen Daten an diese externen Stellen erforderlich. Wir geben personenbezogene Daten nur dann an externe Stellen weiter, wenn dies im Rahmen einer Vertragserf&uuml;llung erforderlich ist, wenn wir gesetzlich hierzu verpflichtet sind, wenn wir ein berechtigtes Interesse nach Art. 6 Abs. 1 lit. f DSGVO an der Weitergabe haben oder wenn eine sonstige Rechtsgrundlage die Datenweitergabe erlaubt. Beim Einsatz von Auftragsverarbeitern geben wir personenbezogene Daten unserer Kunden nur auf Grundlage eines g&uuml;ltigen Vertrags &uuml;ber Auftragsverarbeitung weiter.</p>
<h4>Widerruf Ihrer Einwilligung zur Datenverarbeitung</h4>
<p>Viele Datenverarbeitungsvorg&auml;nge sind nur mit Ihrer ausdr&uuml;cklichen Einwilligung m&ouml;glich. Sie k&ouml;nnen eine bereits erteilte Einwilligung jederzeit widerrufen. Die Rechtm&auml;&szlig;igkeit der bis zum Widerruf erfolgten Datenverarbeitung bleibt vom Widerruf unber&uuml;hrt.</p>
<h4>Widerspruchsrecht gegen die Datenerhebung in besonderen F&auml;llen sowie gegen Direktwerbung (Art. 21 DSGVO)</h4>
<p>WENN DIE DATENVERARBEITUNG AUF GRUNDLAGE VON ART. 6 ABS. 1 LIT. E ODER F DSGVO ERFOLGT, HABEN SIE JEDERZEIT DAS RECHT, AUS GR&Uuml;NDEN, DIE SICH AUS IHRER BESONDEREN SITUATION ERGEBEN, GEGEN DIE VERARBEITUNG IHRER PERSONENBEZOGENEN DATEN WIDERSPRUCH EINZULEGEN; DIES GILT AUCH F&Uuml;R EIN AUF DIESE BESTIMMUNGEN GEST&Uuml;TZTES PROFILING. WENN SIE WIDERSPRUCH EINLEGEN, WERDEN WIR IHRE BETROFFENEN PERSONENBEZOGENEN DATEN NICHT MEHR VERARBEITEN, ES SEI DENN, WIR K&Ouml;NNEN ZWINGENDE SCHUTZW&Uuml;RDIGE GR&Uuml;NDE F&Uuml;R DIE VERARBEITUNG NACHWEISEN, DIE IHRE INTERESSEN, RECHTE UND FREIHEITEN &Uuml;BERWIEGEN ODER DIE VERARBEITUNG DIENT DER GELTENDMACHUNG, AUS&Uuml;BUNG ODER VERTEIDIGUNG VON RECHTSANSPR&Uuml;CHEN (WIDERSPRUCH NACH ART. 21 ABS. 1 DSGVO).</p>
<h4>Beschwerderecht bei der zust&auml;ndigen Aufsichtsbeh&ouml;rde</h4>
<p>Im Falle von Verst&ouml;&szlig;en gegen die DSGVO steht den Betroffenen ein Beschwerderecht bei einer Aufsichtsbeh&ouml;rde, insbesondere in dem Mitgliedstaat ihres gew&ouml;hnlichen Aufenthalts, ihres Arbeitsplatzes oder des Orts des mutma&szlig;lichen Versto&szlig;es zu.</p>
<h4>Recht auf Daten&uuml;bertragbarkeit</h4>
<p>Sie haben das Recht, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erf&uuml;llung eines Vertrags automatisiert verarbeiten, an sich oder an einen Dritten in einem g&auml;ngigen, maschinenlesbaren Format aush&auml;ndigen zu lassen. Sofern Sie die direkte &Uuml;bertragung der Daten an einen anderen Verantwortlichen verlangen, erfolgt dies nur, soweit es technisch machbar ist.</p>
<h4>Auskunft, Berichtigung und L&ouml;schung</h4>
<p>Sie haben im Rahmen der geltenden gesetzlichen Bestimmungen jederzeit das Recht auf unentgeltliche Auskunft &uuml;ber Ihre gespeicherten personenbezogenen Daten, deren Herkunft und Empf&auml;nger und den Zweck der Datenverarbeitung und ggf. ein Recht auf Berichtigung oder L&ouml;schung dieser Daten.</p>
<h4>Recht auf Einschr&auml;nkung der Verarbeitung</h4>
<p>Sie haben das Recht, die Einschr&auml;nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Hierzu k&ouml;nnen Sie sich jederzeit an uns wenden.</p>
<h4>SSL- bzw. TLS-Verschl&uuml;sselung</h4>
<p>Diese Seite nutzt aus Sicherheitsgr&uuml;nden und zum Schutz der &Uuml;bertragung vertraulicher Inhalte eine SSL- bzw. TLS-Verschl&uuml;sselung. Eine verschl&uuml;sselte Verbindung erkennen Sie daran, dass die Adresszeile des Browsers von &bdquo;http://&ldquo; auf &bdquo;https://&ldquo; wechselt und an dem Schloss-Symbol in Ihrer Browserzeile.</p>
<h4>Widerspruch gegen Werbe-E-Mails</h4>
<p>Der Nutzung von im Rahmen der Impressumspflicht ver&ouml;ffentlichten Kontaktdaten zur &Uuml;bersendung von nicht ausdr&uuml;cklich angeforderter Werbung und Informationsmaterialien wird hiermit widersprochen. Die Betreiber der Seiten behalten sich ausdr&uuml;cklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-E-Mails, vor.</p>

<h3>4. Datenerfassung auf dieser Website</h3>
<h4>Cookies</h4>
<p>Diese Website verwendet keine Cookies und keine Analyse- oder Tracking-Werkzeuge. Schriftarten und Programmbibliotheken werden lokal von unserem eigenen Server ausgeliefert; beim Seitenaufruf werden keine Daten an Dritte (etwa Google Fonts oder ein CDN) &uuml;bertragen.</p>
<h4>Server-Log-Dateien</h4>
<p>Der Provider der Seiten erhebt und speichert automatisch Informationen in so genannten Server-Log-Dateien, die Ihr Browser automatisch an uns &uuml;bermittelt. Dies sind: Browsertyp und Browserversion, verwendetes Betriebssystem, Referrer URL, Hostname des zugreifenden Rechners, Uhrzeit der Serveranfrage und die IP-Adresse. Eine Zusammenf&uuml;hrung dieser Daten mit anderen Datenquellen wird nicht vorgenommen. Die Erfassung dieser Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Der Websitebetreiber hat ein berechtigtes Interesse an der technisch fehlerfreien Darstellung und der Optimierung seiner Website.</p>
<h4>Anfrage per E-Mail, Telefon oder Telefax</h4>
<p>Wenn Sie uns per E-Mail, Telefon oder Telefax kontaktieren, wird Ihre Anfrage inklusive aller daraus hervorgehenden personenbezogenen Daten (Name, Anfrage) zum Zwecke der Bearbeitung Ihres Anliegens bei uns gespeichert und verarbeitet. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter. Die Verarbeitung dieser Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, sofern Ihre Anfrage mit der Erf&uuml;llung eines Vertrags zusammenh&auml;ngt oder zur Durchf&uuml;hrung vorvertraglicher Ma&szlig;nahmen erforderlich ist. In allen &uuml;brigen F&auml;llen beruht die Verarbeitung auf unserem berechtigten Interesse an der effektiven Bearbeitung der an uns gerichteten Anfragen (Art. 6 Abs. 1 lit. f DSGVO) oder auf Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO).</p>
<h4>Kommunikation via WhatsApp</h4>
<p>F&uuml;r die Kommunikation mit unseren Kunden und sonstigen Dritten nutzen wir unter anderem den Instant-Messaging-Dienst WhatsApp. Anbieter ist die WhatsApp Ireland Limited, Merrion Road, Dublin 4, D04 X2K5, Irland.</p>
<p>Die Kommunikation erfolgt &uuml;ber eine Ende-zu-Ende-Verschl&uuml;sselung (Peer-to-Peer), die verhindert, dass WhatsApp oder sonstige Dritte Zugriff auf die Kommunikationsinhalte erlangen k&ouml;nnen. WhatsApp erh&auml;lt jedoch Zugriff auf Metadaten, die im Zuge des Kommunikationsvorgangs entstehen (z.&nbsp;B. Absender, Empf&auml;nger und Zeitpunkt). Wir weisen ferner darauf hin, dass WhatsApp nach eigener Aussage personenbezogene Daten seiner Nutzer mit seiner in den USA ans&auml;ssigen Konzernmutter Meta teilt. Weitere Details finden Sie in der Datenschutzrichtlinie von WhatsApp unter: <a href="https://www.whatsapp.com/legal/#privacy-policy" target="_blank" rel="noopener noreferrer">https://www.whatsapp.com/legal/#privacy-policy</a>.</p>
<p>Der Einsatz von WhatsApp erfolgt auf Grundlage unseres berechtigten Interesses an einer m&ouml;glichst schnellen und effektiven Kommunikation (Art. 6 Abs. 1 lit. f DSGVO). Sofern eine entsprechende Einwilligung abgefragt wurde, erfolgt die Datenverarbeitung ausschlie&szlig;lich auf Grundlage der Einwilligung; diese ist jederzeit mit Wirkung f&uuml;r die Zukunft widerrufbar. Wir nutzen WhatsApp in der Variante &bdquo;WhatsApp Business&ldquo;. Die Daten&uuml;bertragung in die USA wird auf die Standardvertragsklauseln der EU-Kommission gest&uuml;tzt; WhatsApp ist zudem nach dem EU-US Data Privacy Framework zertifiziert. Wir haben unsere WhatsApp-Accounts so eingestellt, dass kein automatischer Datenabgleich mit dem Adressbuch der eingesetzten Smartphones erfolgt.</p>

<h3>5. Traumdeutung: Verarbeitung Ihrer Trauminhalte</h3>
<h4>Besondere Kategorien personenbezogener Daten</h4>
<p>Zur Erbringung der Traumdeutung verarbeiten wir den von Ihnen eingereichten Trauminhalt, Ihren Namen, Ihre Kontaktdaten sowie den von Ihnen mitgeteilten Lebenskontext. Trauminhalte k&ouml;nnen besondere Kategorien personenbezogener Daten im Sinne von Art. 9 Abs. 1 DSGVO umfassen (z.&nbsp;B. Hinweise auf Gesundheit, religi&ouml;se oder weltanschauliche &Uuml;berzeugungen, Sexualleben oder Beziehungen). Die Verarbeitung dieser Inhalte erfolgt ausschlie&szlig;lich auf Grundlage Ihrer ausdr&uuml;cklichen Einwilligung gem&auml;&szlig; Art. 6 Abs. 1 lit. a und Art. 9 Abs. 2 lit. a DSGVO, die Sie vor der Einreichung Ihres Traumes erteilen. Ohne diese Einwilligung kann die Deutung nicht erbracht werden. Ihre Einwilligung ist jederzeit mit Wirkung f&uuml;r die Zukunft widerrufbar.</p>
<h4>Speicherung und Archivierung (Proton)</h4>
<p>Ihre Trauminhalte, Ihr Name, Ihre Kontaktdaten und der mitgeteilte Lebenskontext werden zur Bearbeitung und Archivierung bei der Proton AG gespeichert (Proton Mail f&uuml;r die Korrespondenz, Proton Drive f&uuml;r die Archivierung, Proton Docs f&uuml;r die Erstellung der Deutung). Anbieter ist die Proton AG, Route de la Galaise 32, 1228 Plan-les-Ouates, Schweiz.</p>
<p>Die Schweiz verf&uuml;gt &uuml;ber einen Angemessenheitsbeschluss der EU-Kommission (Art. 45 DSGVO); eine &Uuml;bermittlung in ein unsicheres Drittland findet hierdurch nicht statt. Proton verschl&uuml;sselt die Inhalte Ende-zu-Ende bzw. im Ruhezustand, sodass der Anbieter selbst keinen Klartextzugriff hat. Mit Proton besteht ein Vertrag &uuml;ber Auftragsverarbeitung (AVV) gem&auml;&szlig; Art. 28 DSGVO.</p>
<p><strong>Speicherdauer:</strong> Trauminhalte und die zugeh&ouml;rige Korrespondenz werden sp&auml;testens 12 Monate nach der letzten f&uuml;r Sie erstellten Deutung gel&ouml;scht. Reichen Sie innerhalb dieses Zeitraums einen weiteren Traum ein, beginnt die Frist neu, damit fr&uuml;here Deutungen f&uuml;r die Kontinuit&auml;t herangezogen werden k&ouml;nnen. Auf Ihren Wunsch l&ouml;schen wir Ihre Daten jederzeit fr&uuml;her. Gesetzliche Aufbewahrungsfristen (z.&nbsp;B. f&uuml;r Rechnungen) bleiben unber&uuml;hrt.</p>
<h4>KI-gest&uuml;tzte Erstellung der Traumdeutung (Anthropic Claude)</h4>
<p>Zur Unterst&uuml;tzung bei der Erstellung Ihrer schriftlichen Traumdeutung nutze ich das KI-Werkzeug &bdquo;Claude&ldquo; der Anthropic PBC, 548 Market Street, PMB 90375, San Francisco, CA 94104, USA. Die Aisling-Lesart, die Methode und das letzte Wort liegen bei mir; die KI dient der &Uuml;bersetzung, Strukturierung und dem Ausformulieren.</p>
<p>Vor der Verarbeitung entferne ich, soweit m&ouml;glich, Ihren Namen und unmittelbar identifizierende Angaben aus dem Trauminhalt (Pseudonymisierung). In meinem Nutzerkonto ist die Verwendung meiner Eingaben zu Trainingszwecken deaktiviert.</p>
<p>Rechtsgrundlage ist Ihre ausdr&uuml;ckliche Einwilligung gem&auml;&szlig; Art. 6 Abs. 1 lit. a und Art. 9 Abs. 2 lit. a DSGVO. Die &Uuml;bermittlung in die USA erfolgt auf Grundlage geeigneter Garantien (EU-Standardvertragsklauseln). Weitere Informationen zur Datenverarbeitung durch Anthropic: <a href="https://www.anthropic.com/legal/privacy" target="_blank" rel="noopener noreferrer">https://www.anthropic.com/legal/privacy</a>.</p>
<h4>Bewertungen (ProvenExpert)</h4>
<p>Auf dieser Website ist ein statisches Bewertungssiegel eingebunden, das auf unser &ouml;ffentliches Profil bei ProvenExpert verlinkt. Das Siegel wird als Bilddatei von unserem eigenen Server ausgeliefert; beim Aufruf der Website werden hierdurch keine Daten an ProvenExpert &uuml;bertragen. Erst wenn Sie das Siegel anklicken, werden Sie zur externen Website der ProvenExpert GmbH, Quedlinburger Str. 1, 10589 Berlin, weitergeleitet, f&uuml;r deren Datenverarbeitung deren Datenschutzerkl&auml;rung gilt. Kundenbewertungen werden &uuml;ber ProvenExpert erhoben; die &Uuml;bermittlung Ihrer Angaben erfolgt dabei durch Sie selbst unmittelbar an ProvenExpert. Rechtsgrundlage f&uuml;r die Einbindung des verlinkten Siegels ist unser berechtigtes Interesse an der transparenten Darstellung gepr&uuml;fter Kundenbewertungen (Art. 6 Abs. 1 lit. f DSGVO).</p>
`
};
